conky.config = {

    update_interval = 1,
    total_run_times = 0,
    background = true,
    no_buffers = true,

    cpu_avg_samples = 2,
    net_avg_samples = 2,
    override_utf8_locale = true,

    -- window (safe background mode)
    own_window = true,
    own_window_type = 'override',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 0,

    double_buffer = true,

    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
   alignment = 'top_left',
   gap_x = 20,
   gap_y = 20,
    -- layout
    alignment = 'top_right',
    gap_x = 30,
    gap_y = 45,
    minimum_width = 260,

    -- fonts
    use_xft = true,
    font = 'BitCountSingle:size=11',
    xftalpha = 0.95,

    -- colors (pure white theme)
    default_color = 'ffffff',
    color1 = 'f0f0f0',
    color2 = 'd9d9d9',
    color3 = 'bfbfbf',
};

conky.text = [[


${font Orbitron:size=40}${time %H:%M:%S}
${font BitcountSingle:size=13}${time %A, %d %b %Y}

${hr 1}

${font Silkscreen:size=12}${color2}SYSTEM:${color}${font}
host:   ${nodename}
uptime: ${uptime_short}

${hr 1}

${font Silkscreen:size=12}${color2}CPU:${color}${font}
${cpu}% ${cpubar 6}


${font Silkscreen:size=12}${color2}MEMORY:${color}${font}
${memperc}% ${membar 6}


${font Silkscreen:size=12}${color2}DISK:${color}${font}
root ${fs_used_perc /}% ${fs_bar 6 /}




]];
